--_ignore_exceptions_=on
DROP TABLE RIGHTS_PROFILERIGHTS;
DROP TABLE RIGHTS_GROUPRIGHTS;
DROP TABLE RIGHTS_USERRIGHTS;
DROP TABLE RIGHTS_PROFILE;
DROP TABLE GROUPS_USERS;
DROP TABLE GROUPS;
DROP TABLE USERS;
DROP TABLE USERPREFERENCES;
DROP SEQUENCE SEQ_GROUPS;
DROP SEQUENCE SEQ_RIGHTS_PROFILE;
