--
--  Copyright 2016 Anyware Services
--
--  Licensed under the Apache License, Version 2.0 (the "License");
--  you may not use this file except in compliance with the License.
--  You may obtain a copy of the License at
--
--      http://www.apache.org/licenses/LICENSE-2.0
--
--  Unless required by applicable law or agreed to in writing, software
--  distributed under the License is distributed on an "AS IS" BASIS,
--  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--  See the License for the specific language governing permissions and
--  limitations under the License.
--

--_ignore_exceptions_=on
DROP TABLE RIGHTS_PROFILERIGHTS IF EXISTS;

DROP TABLE RIGHTS_ALLOWEDGROUPS IF EXISTS;
DROP TABLE RIGHTS_ALLOWEDUSERS IF EXISTS;
DROP TABLE RIGHTS_DENIEDGROUPS IF EXISTS;
DROP TABLE RIGHTS_DENIEDUSERS IF EXISTS;
DROP TABLE RIGHTS_ALLOWEDPROFILESANYCON IF EXISTS;
DROP TABLE RIGHTS_DENIEDPROFILESANYCON IF EXISTS;
DROP TABLE RIGHTS_ALLOWEDPROFILESANONYM IF EXISTS;
DROP TABLE RIGHTS_DENIEDPROFILESANONYM IF EXISTS;

DROP TABLE RIGHTS_PROFILE IF EXISTS;

DROP TABLE USERPOPULATIONSBYCONTEXT IF EXISTS;
DROP TABLE GROUPDIRECTORIESBYCONTEXT IF EXISTS;

DROP TABLE ADMINUSERS IF EXISTS;
DROP TABLE GROUPS_USERS IF EXISTS;
DROP TABLE GROUPS IF EXISTS;
DROP TABLE USERS IF EXISTS;

DROP TABLE USERPREFERENCES IF EXISTS;
DROP SEQUENCE SEQ_GROUPS IF EXISTS;
DROP SEQUENCE SEQ_RIGHTS_PROFILE IF EXISTS;
DROP SEQUENCE SEQ_PROFILE_ASSIGNMENTS IF EXISTS;
