/*
 * OUTILS
 */
   var factory;
   
   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-rights-assignment","toolClass":"Ametys.plugins.cms.right.RightsAssignmentTool","title":"Assignation des profils","description":"Accès à l'écran de gestion des assignations de profils aux utilisateurs et aux groupes sur le contexte courant.","description-footer":"Voir l'aide pour plus de détails","icon-small":"/plugins/cms/resources/img/rights/assign_16.gif","icon-medium":"/plugins/cms/resources/img/rights/assign_32.gif","icon-large":"/plugins/cms/resources/img/rights/assign_50.gif","default-location":""}, {id: "org.ametys.cms.rights.RightsAssignmentFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"toolClass":"Ametys.plugins.cms.content.tool.OldContentTool","role":"uitool-old-content","description":"<u>Auteur</u> : <b></b><br/><u>Dernière modification</u> :<b></b>","description-footer":"Voir l'aide pour plus de détails","icon-small":"/plugins/cms/resources/img/history/content/old_content_16.png","icon-medium":"/plugins/cms/resources/img/history/content/old_content_32.png","icon-large":"/plugins/cms/resources/img/history/content/old_content_48.png","default-location":"c"}, {id: "org.ametys.cms.OldContentFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-explorer-tool","toolClass":"Ametys.plugins.explorer.tool.ExplorerTool","tree-ignore-files":"false","title":"Explorateur de ressources","description":"Bibliothèque de documents partagés, calendrier, fils de discussion, ...","help":"org.ametys.explorer.resourcesexplorer","icon-small":"/plugins/web/resources/img/explorer/menu/icon_16.png","icon-medium":"/plugins/web/resources/img/explorer/menu/icon_32.png","icon-large":"/plugins/web/resources/img/explorer/menu/icon_48.png","default-location":"l"}, {id: "org.ametys.web.explorer.ExplorerTreeFactory", pluginName: "web"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"toolClass":"Ametys.plugins.cms.content.tool.UnlockTool","role":"uitool-unlock","title":"Déverrouillage des contenus","description":"Déverrouiller les contenus","help":"org.ametys.cms.unlock","icon-small":"/plugins/cms/resources/img/lock/unlock_16.png","icon-medium":"/plugins/cms/resources/img/lock/unlock_32.png","icon-large":"/plugins/cms/resources/img/lock/unlock_48.png","default-location":""}, {id: "org.ametys.cms.userinterface.UnlockFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"toolClass":"Ametys.plugins.cms.iframe.IframeTool","role":"uitool-iframe","title":"Iframe","description":"Outil permettant d'ouvrir une page externe dans le CMS","icon-small":"/plugins/cms/resources/img/iframe/iframe_16.png","icon-medium":"/plugins/cms/resources/img/iframe/iframe_32.png","icon-large":"/plugins/cms/resources/img/iframe/iframe_48.png","default-location":""}, {id: "org.ametys.cms.IframeToolFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-sitemap","toolClass":"Ametys.plugins.web.sitemap.SitemapTool","title":"Plan du site","description":"Arborescence du site courant","icon-small":"/plugins/web/resources/img/sitemap/sitemap_16.png","icon-medium":"/plugins/web/resources/img/sitemap/sitemap_32.png","icon-large":"/plugins/web/resources/img/sitemap/sitemap_50.png","default-location":"l"}, {id: "org.ametys.web.userinterface.SitemapFactory", pluginName: "web"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-repository-console-result","toolClass":"Ametys.repository.ConsoleResultTool","title":"Résultats","description":"Cet outil présente les résultats d'exécution des scripts.","help":"org.ametys.repository.console.result","icon-small":"/plugins/repositoryapp/resources/img/console/console-result-16.png","icon-medium":"/plugins/repositoryapp/resources/img/console/console-result-32.png","icon-large":"/plugins/repositoryapp/resources/img/console/console-result-48.png","default-location":"r"}, {id: "org.ametys.repository.ui.ConsoleResultTool", pluginName: "repositoryapp"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-repository-console","toolClass":"Ametys.repository.ConsoleTool","title":"Console","description":"La console du repository permet d'écrire et exécuter des scripts avec la syntaxe javascript.","help":"org.ametys.repository.console","icon-small":"/plugins/repositoryapp/resources/img/console/console-16.png","icon-medium":"/plugins/repositoryapp/resources/img/console/console-32.png","icon-large":"/plugins/repositoryapp/resources/img/console/console-48.png","default-location":""}, {id: "org.ametys.repository.ui.ConsoleTool", pluginName: "repositoryapp"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"toolClass":"Ametys.plugins.cms.content.tool.PropertiesTool","role":"uitool-properties","title":"Propriétés","description":"Propriétés d'un contenu","selection-target-type":"^(content|simple-content)$","selection-description-empty":"Aucun contenu n'est actuellement sélectionné.<br/>Sélectionnez un contenu pour avoir plus de détails.","selection-description-nomatch":"Aucun contenu n'est actuellement sélectionné.<br/>Sélectionnez un contenu pour avoir plus de détails.","selection-description-multiselectionforbidden":"Plusieurs contenus sont actuellement sélectionnés.<br/>Sélectionnez un contenu pour avoir plus de détails.","icon-small":"/plugins/cms/resources/img/details/properties_16.png","icon-medium":"/plugins/cms/resources/img/details/properties_32.png","icon-large":"/plugins/cms/resources/img/details/properties_48.png","default-location":"l"}, {id: "org.ametys.cms.DetailsFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-fo-groups","toolClass":"Ametys.plugins.core.groups.GroupsTool","groups-manager-role":"org.ametys.core.group.GroupsManager.FO","users-manager-role":"org.ametys.core.user.UsersManager.FO","group-target-type":"fo-group","user-target-type":"fo-user","title":"Groupes du site","description":"Listes des groupes d'utilisateurs pouvant se connecter au site","footer":"Voir l'aide pour plus de détails","icon-small":"/plugins/web/resources/img/groups/fo_group_16.png","icon-medium":"/plugins/web/resources/img/groups/fo_group_32.png","icon-large":"/plugins/web/resources/img/groups/fo_group_48.png","default-location":"c"}, {id: "org.ametys.web.FOGroupsFactory", pluginName: "web"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"toolClass":"Ametys.plugins.dashboard.DashboardTool","role":"uitool-dashboard","title":"Tableau de bord","description":"Le tableau de bord correspond à la liste de vos actions en cours : contenus modifiés récemment, contenus à valider, ...","footer":"Voir l'aide pour plus de détails","icon-small":"/plugins/dashboard/resources/img/dashboard/icon_small.png","icon-medium":"/plugins/dashboard/resources/img/dashboard/icon_medium.png","icon-large":"/plugins/dashboard/resources/img/dashboard/icon_large.png","default-location":"cl"}, {id: "org.ametys.dashboard.ToolFactory", pluginName: "dashboard"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-pageaccess","toolClass":"Ametys.plugins.web.pageaccess.PageAccessTool","title":"Limiter l'accès","description":"Cliquez ici pour limiter l'accès à cette page ou à ce plan du site dans le front-office à des utilisateurs et groupes fixés.","icon-small":"/plugins/web/resources/img/pageaccess/limit_access_16.png","icon-medium":"/plugins/web/resources/img/pageaccess/limit_access_32.png","icon-large":"/plugins/web/resources/img/pageaccess/limit_access_50.png","default-location":"c"}, {id: "org.ametys.web.pageaccess.SetPageAccessFactory", pluginName: "web"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-profiles","toolClass":"Ametys.plugins.core.profiles.ProfilesTool","title":"Profils de droits","description":"Gestion des profils de droits.<br/>Un profil est un ensemble de droits. Chaque utilisateur possède un profil qui permet de connaître la liste de ses droits.","help":"org.ametys.core.rights.profiles","icon-small":"/plugins/core/resources/img/profiles/profile_16.gif","icon-medium":"/plugins/core/resources/img/profiles/profile_32.gif","icon-large":"/plugins/core/resources/img/profiles/profile_50.gif","default-location":""}, {id: "org.ametys.core.ProfilesFactory", pluginName: "core"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-alias","toolClass":"Ametys.plugins.web.alias.AliasTool","title":"Redirections d'URL","description":"Cet outil permet de créer des alias afin de rediriger \"à la volée\" des anciennes url vers des pages ou url existantes.","icon-small":"/plugins/web/resources/img/alias/icon_small.png","icon-medium":"/plugins/web/resources/img/alias/icon_medium.png","icon-large":"/plugins/web/resources/img/alias/icon_large.png"}, {id: "org.ametys.web.userinterface.AliasFactory", pluginName: "web"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"toolClass":"Ametys.plugins.datainclusion.DataSourcesTool","role":"uitool-datasources","title":"Sources de données","description":"Définir des sources de données pour les données fusionnées.","footer":"","icon-small":"/plugins/datainclusion/resources/img/datainclusion-small.png","icon-medium":"/plugins/datainclusion/resources/img/datainclusion-medium.png","icon-large":"/plugins/datainclusion/resources/img/datainclusion-large.png","default-location":"l"}, {id: "org.ametys.datainclusion.tool.DataSourcesFactory", pluginName: "datainclusion"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-skineditor","toolClass":"Ametys.plugins.skineditor.SkinEditorTool","title":"Editeur de charte graphique","description":"Cet outil permet de modifier les fichiers d'une charte graphique.","footer":"","icon-small":"/plugins/skineditor/resources/img/skineditor_16.png","icon-medium":"/plugins/skineditor/resources/img/skineditor_32.png","icon-large":"/plugins/skineditor/resources/img/skineditor_48.png","default-location":"l"}, {id: "org.ametys.skineditor.tool.SkinEditorTool", pluginName: "skineditor"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-content-attachments","toolClass":"Ametys.plugins.cms.content.tool.ContentAttachmentsTool","default-location":"r","title":"Pièces jointes du contenu","description":"Module de gestion des pièces jointes.<br/><br/>Ce module permet de lister, organiser, ajouter, supprimer ou télécharger les pièces jointes du contenu courant.","help":"org.ametys.cms.content.attachments","icon-small":"/plugins/cms/resources/img/content/attachments/attachment_16.png","icon-medium":"/plugins/cms/resources/img/content/attachments/attachment_32.png","icon-large":"/plugins/cms/resources/img/content/attachments/attachment_48.png"}, {id: "org.ametys.cms.userinterface.content.AttachmentsTool", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"role":"uitool-skin-config","toolClass":"Ametys.plugins.web.skin.SkinConfigurationTool","title":"Configurer","description":"Modifie la configuration de la charte graphique.","icon-small":"/plugins/web/resources/img/administrator/skins/configure_16.png","icon-medium":"/plugins/web/resources/img/administrator/skins/configure_32.png","icon-large":"/plugins/web/resources/img/administrator/skins/configure_48.png"}, {id: "org.ametys.web.skin.SkinConfigurationFactory", pluginName: "web"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"toolClass":"Ametys.plugins.newsletter.NewslettersTool","role":"uitool-newsletters","title":"Lettre d'information","description":"Gestion de la lettre d'information et des catégories","footer":"Voir l'aide pour plus de détails","icon-small":"/plugins/newsletter/resources/img/newsletters_16.png","icon-medium":"/plugins/newsletter/resources/img/newsletters_32.png","icon-large":"/plugins/newsletter/resources/img/newsletters_48.png","default-location":"l"}, {id: "org.ametys.newsletter.userinterface.NewslettersFactory", pluginName: "newsletter"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"toolClass":"Ametys.plugins.cms.content.tool.CommentsTool","role":"uitool-content-comments","title":"Commentaires","description":"Voir les commentaires des contenus actuellement sélectionnés.","help":"org.ametys.cms.content.comments","selection-target-type":"^content$","selection-enable-multiselection":"true","selection-description-empty":"Aucun contenu n'est actuellement sélectionné.<br/>Sélectionnez un contenu pour voir ses commentaires.","selection-description-nomatch":"Aucun contenu n'est actuellement sélectionné.<br/>Sélectionnez un contenu pour voir ses commentaires.","icon-small":"/plugins/cms/resources/img/content/comments/comments_16.png","icon-medium":"/plugins/cms/resources/img/content/comments/comments_32.png","icon-large":"/plugins/cms/resources/img/content/comments/comments_48.png","default-location":""}, {id: "org.ametys.cms.repository.comments.CommentsFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-log","toolClass":"Ametys.plugins.cms.system.log.LogTool","title":"Journaux applicatif","description":"Voir les journaux applicatif affichant les événements","description-footer":"Voir l'aide pour plus de détails","icon-small":"/plugins/cms/resources/img/logs/logs_16.png","icon-medium":"/plugins/cms/resources/img/logs/logs_32.png","icon-large":"/plugins/cms/resources/img/logs/logs_48.png","default-location":"b"}, {id: "org.ametys.cms.userinterface.LogFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-params-editor","toolClass":"Ametys.plugins.cms.params.tool.ParameterFilesTool","title":"Fichiers de paramètres","description":"Cet outil permet de modifier les fichiers de paramètres de l'application.","description-footer":"","icon-small":"/plugins/cms/resources/img/params/params_16.png","icon-medium":"/plugins/cms/resources/img/params/params_32.png","icon-large":"/plugins/cms/resources/img/params/params_48.png","default-location":"l"}, {id: "org.ametys.cms.params.ParametersToolFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"toolClass":"Ametys.plugins.cms.params.tool.ParameterFileEditorTool","role":"uitool-file-editor","title":"Fichier de paramètre","description":"Cet outil permet d'éditer un fichier de paramètre.","icon-small":"/plugins/cms/resources/img/params/editor/mixed_16.png","icon-medium":"/plugins/cms/resources/img/params/editor/mixed_32.png","icon-large":"/plugins/cms/resources/img/params/editor/mixed_48.png","default-location":""}, {id: "Ametys.plugins.cms.params.FileEditorToolFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-messagestracker","toolClass":"Ametys.plugins.coreui.system.messagetracker.MessageTrackerTool","title":"Suivi des messages du bus","description":"Voir les messages du bus","help":"org.ametys.runtime.messagetracker","icon-small":"/plugins/core-ui/resources/img/messages/messages_16.png","icon-medium":"/plugins/core-ui/resources/img/messages/messages_32.png","icon-large":"/plugins/core-ui/resources/img/messages/messages_48.png","default-location":"b"}, {id: "org.ametys.runtime.userinterface.MessageTrackerFactory", pluginName: "core-ui"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"toolClass":"Ametys.plugins.cms.content.tool.SimpleContentsEditionTool","role":"uitool-simple-contents","title":"Contenus simples","description":"Cet outil permet d'éditer les contenus simples dans un tableau.","help":"org.ametys.cms.simplecontents","icon-small":"/plugins/cms/resources/img/simple-content/edition_grid_16.png","icon-medium":"/plugins/cms/resources/img/simple-content/edition_grid_32.png","icon-large":"/plugins/cms/resources/img/simple-content/edition_grid_48.png","default-location":""}, {id: "org.ametys.cms.SimpleContentsFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-tags","toolClass":"Ametys.plugins.web.tag.TagsTool","title":"Etiquettes","description":"Gestion des étiquettes applicative","description-footer":"Voir l'aide pour plus de détails","icon-small":"/plugins/cms/resources/img/tag/tags_16.png","icon-medium":"/plugins/cms/resources/img/tag/tags_32.png","icon-large":"/plugins/cms/resources/img/tag/tags_50.png","default-location":"l"}, {id: "org.ametys.web.userinterface.TagsFactory", pluginName: "web"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"role":"uitool-admin-site-statistics","toolClass":"Ametys.plugins.web.site.SiteStatisticsTool","title":"Statistiques du site","description":"Cet outil permet de visualiser les statistiques du site","icon-small":"/plugins/web/resources/img/site/statistics_16.png","icon-medium":"/plugins/web/resources/img/site/statistics_32.png","icon-large":"/plugins/web/resources/img/site/statistics_48.png"}, {id: "org.ametys.web.admin.SiteStatisticsFactory", pluginName: "web"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"role":"uitool-admin-site-config","toolClass":"Ametys.plugins.web.site.SiteConfigurationTool","title":"Configurer","description":"Modifie la configuration du site.<br/><br/>Naviguez en utilisant les onglets et modifiez les valeurs des paramètres.","icon-small":"/plugins/web/resources/img/site/configure_site_16.png","icon-medium":"/plugins/web/resources/img/site/configure_site_32.png","icon-large":"/plugins/web/resources/img/site/configure_site_48.png"}, {id: "org.ametys.web.admin.SiteConfigurationFactory", pluginName: "web"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"role":"uitool-admin-global-statistics","toolClass":"Ametys.plugins.web.site.GlobalStatisticsTool","title":"Statistiques globales","description":"Voir les statistiques sur l'ensemble des sites","icon-small":"/plugins/web/resources/img/site/statistics_16.png","icon-medium":"/plugins/web/resources/img/site/statistics_32.png","icon-large":"/plugins/web/resources/img/site/statistics_48.png"}, {id: "org.ametys.web.admin.GlobalStatisticsFactory", pluginName: "web"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-admin-sites","toolClass":"Ametys.plugins.web.site.SitesTool","title":"Sites","description":"Cet outil permet de gérer et configurer les sites","icon-small":"/plugins/web/resources/img/site/site_16.png","icon-medium":"/plugins/web/resources/img/site/site_32.png","icon-large":"/plugins/web/resources/img/site/site_48.png"}, {id: "org.ametys.web.admin.SitesFactory", pluginName: "web"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-admin-monitoring","toolClass":"Ametys.plugins.admin.jvmstatus.MonitoringTool","title":"Monitoring","description":"Cet outil vous permet de visualiser les courbes de suivi de l'état du système.","icon-small":"/plugins/admin/resources/img/jvmstatus/monitoring_16.png","icon-medium":"/plugins/admin/resources/img/jvmstatus/monitoring_32.png","icon-large":"/plugins/admin/resources/img/jvmstatus/monitoring_48.png"}, {id: "org.ametys.plugins.admin.MonitoringFactory", pluginName: "admin"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-admin-jvmstatus","toolClass":"Ametys.plugins.admin.jvmstatus.JVMStatusTool","title":"Général","description":"Cet outil vous permet de consulter l'état général du système et de la JVM","icon-small":"/plugins/admin/resources/img/jvmstatus/jvmstatus_16.png","icon-medium":"/plugins/admin/resources/img/jvmstatus/jvmstatus_32.png","icon-large":"/plugins/admin/resources/img/jvmstatus/jvmstatus_48.png","default-location":"cl"}, {id: "org.ametys.plugins.admin.JVMStatusFactory", pluginName: "admin"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-admin-systemproperties","toolClass":"Ametys.plugins.admin.jvmstatus.SystemPropertiesTool","title":"Propriétés du système","description":"Cet outil vous permet de visualiser les propriétés système de lancement de la machine virtuelle java.","icon-small":"/plugins/admin/resources/img/jvmstatus/properties_16.png","icon-medium":"/plugins/admin/resources/img/jvmstatus/properties_32.png","icon-large":"/plugins/admin/resources/img/jvmstatus/properties_48.png","default-location":"cl"}, {id: "org.ametys.plugins.admin.SystemPropertiesFactory", pluginName: "admin"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"toolClass":"Ametys.plugins.cms.navhistory.NavHistoryTool","role":"uitool-navhistory","title":"Historique de navigation","description":"Cet outil trace les actions principales effectuées depuis votre dernière connexion (contenus consultés, recherches effectuées, ...)","help":"org.ametys.cms.navhistory","icon-small":"/plugins/cms/resources/img/navhistory/history_16.png","icon-medium":"/plugins/cms/resources/img/navhistory/history_32.png","icon-large":"/plugins/cms/resources/img/navhistory/history_48.png","default-location":"l"}, {id: "org.ametys.cms.userinterface.NavHistoryFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"toolClass":"Ametys.plugins.linkdirectory.link.LinkDirectoryTool","role":"uitool-linkdirectory","title":"Annuaire de liens","description":"Interface de gestion des liens de l'annuaire.","footer":"Voir l'aide pour plus de détails.","icon-small":"/plugins/link-directory/resources/img/link-directory-16.png","icon-medium":"/plugins/link-directory/resources/img/link-directory-32.png","icon-large":"/plugins/link-directory/resources/img/link-directory-48.png","default-location":""}, {id: "org.ametys.plugins.linkdirectory.ui.LinkDirectoryTool", pluginName: "link-directory"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-admin-system","toolClass":"Ametys.plugins.admin.tool.SystemTool","title":"Accès","description":"Cet outil permet de mettre en place une annonce d'accueil pour les utilisateurs.","icon-small":"/plugins/admin/resources/img/system/announcement_16.png","icon-medium":"/plugins/admin/resources/img/system/announcement_32.png","icon-large":"/plugins/admin/resources/img/system/announcement_48.png","default-location":"cl"}, {id: "org.ametys.plugins.admin.system.SystemFactory", pluginName: "admin"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"toolClass":"Ametys.plugins.cms.content.tool.SearchArchivesTool","role":"uitool-archive-search","title":"Rechercher dans les archives","description":"Outil de recherche sur les contenus archivés.","help":"org.ametys.cms.archives.search","icon-small":"/plugins/cms/resources/img/search/search_archives_16.png","icon-medium":"/plugins/cms/resources/img/search/search_archives_32.png","icon-large":"/plugins/cms/resources/img/search/search_archives_48.png","default-location":"","content-type-0-value":"org.ametys.plugins.multimedia.Content.audioGallery","content-type-0-label":"Galerie audio","content-type-1-value":"","content-type-1-label":"- Tous -","content-type-2-value":"org.ametys.plugins.news.Content.news","content-type-2-label":"Actualité","content-type-3-value":"org.ametys.plugins.blog.Content.profile","content-type-3-label":"A propos","content-type-4-value":"org.ametys.plugins.multimedia.Content.multimediaGallery","content-type-4-label":"Galerie vidéo","content-type-5-value":"org.ametys.plugins.myfavorites.Content.myfavorites","content-type-5-label":"Liste de liens","content-type-6-value":"org.ametys.plugins.multimedia.Content.photosGallery","content-type-6-label":"Galerie de photos","content-type-7-value":"org.ametys.plugins.newsletter.Content.newsletter","content-type-7-label":"Lettre d'information","content-type-8-value":"org.ametys.plugins.blog.Content.post","content-type-8-label":"Billet","content-type-9-value":"org.ametys.web.default.Content.article","content-type-9-label":"Article","content-type-10-value":"org.ametys.plugins.faq.Content.faq","content-type-10-label":"FAQ"}, {id: "org.ametys.cms.archives.SearchFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.plugins.web.page.tool.PageToolFactory", Ext.apply({"role":"uitool-page","toolClass":"Ametys.plugins.web.page.tool.PageTool","title":"Page","description":"<u>Site</u> : <b>&#123;site&#125;</b><br/><u>Langue</u> :<b>&#123;lang&#125;</b><br/><u>Page</u> : <b>&#123;title&#125;</b><br/><u>Url</u> : <b>&#123;url&#125;</b>","icon-small":"/plugins/web/resources/img/sitemap/page_16.png","icon-medium":"/plugins/web/resources/img/sitemap/page_32.png","icon-large":"/plugins/web/resources/img/sitemap/page_48.png"}, {id: "org.ametys.web.PageFactory", pluginName: "web"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"toolClass":"Ametys.plugins.cms.search.SearchTool","autoRefresh":"false","role":"uitool-blog-search","title":"Recherche","description":"Outil de recherche sur les contenus","help":"org.ametys.plugins.blog.search","icon-small":"/plugins/cms/resources/img/search/icon_small.png","icon-medium":"/plugins/cms/resources/img/search/icon_medium.png","icon-large":"/plugins/cms/resources/img/search/icon_large.png","default-location":"","content-type-0-value":"org.ametys.plugins.multimedia.Content.audioGallery","content-type-0-label":"Galerie audio","content-type-1-value":"","content-type-1-label":"- Tous -","content-type-2-value":"org.ametys.plugins.news.Content.news","content-type-2-label":"Actualité","content-type-3-value":"org.ametys.plugins.blog.Content.profile","content-type-3-label":"A propos","content-type-4-value":"org.ametys.plugins.multimedia.Content.multimediaGallery","content-type-4-label":"Galerie vidéo","content-type-5-value":"org.ametys.plugins.myfavorites.Content.myfavorites","content-type-5-label":"Liste de liens","content-type-6-value":"org.ametys.plugins.multimedia.Content.photosGallery","content-type-6-label":"Galerie de photos","content-type-7-value":"org.ametys.plugins.newsletter.Content.newsletter","content-type-7-label":"Lettre d'information","content-type-8-value":"org.ametys.plugins.blog.Content.post","content-type-8-label":"Billet","content-type-9-value":"org.ametys.web.default.Content.article","content-type-9-label":"Article","content-type-10-value":"org.ametys.plugins.faq.Content.faq","content-type-10-label":"FAQ"}, {id: "org.ametys.plugins.blog.SearchFactory", pluginName: "blog"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"toolClass":"Ametys.plugins.cms.search.ScriptTool","role":"uitool-script","title":"Editeur de script","description":"L'éditeur de script permet d'écrire des requêtes sur la base de contenus","footer":"Voir l'aide pour plus de détails","icon-small":"/plugins/cms/resources/img/search/script/icon_small.png","icon-medium":"/plugins/cms/resources/img/search/script/icon_medium.png","icon-large":"/plugins/cms/resources/img/search/script/icon_large.png","default-location":"","content-type-0-value":"org.ametys.plugins.multimedia.Content.audioGallery","content-type-0-label":"Galerie audio","content-type-1-value":"","content-type-1-label":"- Tous -","content-type-2-value":"org.ametys.plugins.news.Content.news","content-type-2-label":"Actualité","content-type-3-value":"org.ametys.plugins.blog.Content.profile","content-type-3-label":"A propos","content-type-4-value":"org.ametys.plugins.multimedia.Content.multimediaGallery","content-type-4-label":"Galerie vidéo","content-type-5-value":"org.ametys.plugins.myfavorites.Content.myfavorites","content-type-5-label":"Liste de liens","content-type-6-value":"org.ametys.plugins.multimedia.Content.photosGallery","content-type-6-label":"Galerie de photos","content-type-7-value":"org.ametys.plugins.newsletter.Content.newsletter","content-type-7-label":"Lettre d'information","content-type-8-value":"org.ametys.plugins.blog.Content.post","content-type-8-label":"Billet","content-type-9-value":"org.ametys.web.default.Content.article","content-type-9-label":"Article","content-type-10-value":"org.ametys.plugins.faq.Content.faq","content-type-10-label":"FAQ"}, {id: "org.ametys.cms.ScriptSearchFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"toolClass":"Ametys.plugins.cms.search.SearchTool","autoRefresh":"false","role":"uitool-search","title":"Recherche","description":"Outil de recherche sur les contenus","help":"org.ametys.cms.search","icon-small":"/plugins/cms/resources/img/search/icon_small.png","icon-medium":"/plugins/cms/resources/img/search/icon_medium.png","icon-large":"/plugins/cms/resources/img/search/icon_large.png","default-location":"","content-type-0-value":"org.ametys.plugins.multimedia.Content.audioGallery","content-type-0-label":"Galerie audio","content-type-1-value":"","content-type-1-label":"- Tous -","content-type-2-value":"org.ametys.plugins.news.Content.news","content-type-2-label":"Actualité","content-type-3-value":"org.ametys.plugins.blog.Content.profile","content-type-3-label":"A propos","content-type-4-value":"org.ametys.plugins.multimedia.Content.multimediaGallery","content-type-4-label":"Galerie vidéo","content-type-5-value":"org.ametys.plugins.myfavorites.Content.myfavorites","content-type-5-label":"Liste de liens","content-type-6-value":"org.ametys.plugins.multimedia.Content.photosGallery","content-type-6-label":"Galerie de photos","content-type-7-value":"org.ametys.plugins.newsletter.Content.newsletter","content-type-7-label":"Lettre d'information","content-type-8-value":"org.ametys.plugins.blog.Content.post","content-type-8-label":"Billet","content-type-9-value":"org.ametys.web.default.Content.article","content-type-9-label":"Article","content-type-10-value":"org.ametys.plugins.faq.Content.faq","content-type-10-label":"FAQ"}, {id: "org.ametys.cms.SearchFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-fo-users","toolClass":"Ametys.plugins.core.users.UsersTool","users-manager-role":"org.ametys.core.user.UsersManager.FO","message-target-type":"fo-user","title":"Utilisateurs du site","description":"Listes des utilisateurs pouvant se connecter au site","footer":"Voir l'aide pour plus de détails","icon-small":"/plugins/web/resources/img/users/fo_user_16.png","icon-medium":"/plugins/web/resources/img/users/fo_user_32.png","icon-large":"/plugins/web/resources/img/users/fo_user_48.png","default-location":"c"}, {id: "org.ametys.web.FOUsersFactory", pluginName: "web"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-help","toolClass":"Ametys.plugins.coreui.help.HelpTool","title":"Aide","description":"Outil affichant l'aide en ligne","icon-small":"/plugins/cms/resources/img/help/help_16.png","icon-medium":"/plugins/cms/resources/img/help/help_32.png","icon-large":"/plugins/cms/resources/img/help/help_48.png","default-location":"r"}, {id: "org.ametys.coreui.HelpFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-admin-config","toolClass":"Ametys.plugins.admin.config.ConfigTool","title":"Configuration","description":"Réglage des paramètres de configuration","icon-small":"/plugins/admin/resources/img/config/config_16.png","icon-medium":"/plugins/admin/resources/img/config/config_32.png","icon-large":"/plugins/admin/resources/img/config/config_48.png","default-location":"cl"}, {id: "org.ametys.plugins.admin.config.ConfigToolFactory", pluginName: "admin"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"role":"uitool-repository-ametysobject-metadata","toolClass":"Ametys.plugins.repository.AmetysObjectMetadataTool","title":"Métadonnées","description":"Métadonnées de l'objet Ametys.","help":"org.ametys.repository.ametysobject.metadata","icon-small":"/plugins/repository/resources/img/ametys/ametysobject-metadata-16.png","icon-medium":"/plugins/repository/resources/img/ametys/ametysobject-metadata-32.png","icon-large":"/plugins/repository/resources/img/ametys/ametysobject-metadata-48.png","default-location":""}, {id: "org.ametys.repository.ui.AmetysObjectMetadataTool", pluginName: "repository"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-repository-ametys","toolClass":"Ametys.plugins.repository.AmetysViewTool","title":"Vue Ametys","description":"Cet outil montre l'arbre des objets Ametys.","help":"org.ametys.repository.ametysview","icon-small":"/plugins/repository/resources/img/ametys/ametys-view-16.png","icon-medium":"/plugins/repository/resources/img/ametys/ametys-view-32.png","icon-large":"/plugins/repository/resources/img/ametys/ametys-view-48.png","default-location":"l"}, {id: "org.ametys.repository.ui.AmetysViewTool", pluginName: "repository"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-page-properties","toolClass":"Ametys.plugins.web.page.tool.PagePropertiesTool","selection-target-type":"^page$","title":"Propriétés","description":"Propriétés de la page","selection-description-empty":"Aucune page n'est actuellement sélectionnée.<br/>Sélectionnez une page pour voir ses propriétés.","selection-description-nomatch":"Aucune page n'est actuellement sélectionnée.<br/>Sélectionnez une page pour voir ses propriétés.","selection-description-multiselectionforbidden":"Plusieurs pages sont actuellement sélectionnées.<br/>Sélectionnez une page pour ses propriétés.","icon-small":"/plugins/web/resources/img/page/page_properties_16.png","icon-medium":"/plugins/web/resources/img/page/page_properties_32.png","icon-large":"/plugins/web/resources/img/page/page_properties_48.png","default-location":"l"}, {id: "org.ametys.web.page.PropertiesFactory", pluginName: "web"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-skinfactory","toolClass":"Ametys.plugins.skinfactory.tool.SkinFactoryTool","title":"Atelier charte graphique","description":"Personnaliser votre charte graphique","footer":"Voir l'aide pour plus de détails","icon-small":"/plugins/skinfactory/resources/img/skinfactory/skinfactory_16.png","icon-medium":"/plugins/skinfactory/resources/img/skinfactory/skinfactory_32.png","icon-large":"/plugins/skinfactory/resources/img/skinfactory/skinfactory_48.png","default-location":""}, {id: "org.ametys.skinfactory.SkinFactoryTool", pluginName: "skinfactory"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"toolClass":"Ametys.plugins.newsletter.subscribers.SubscribersTool","role":"uitool-newsletter-subscribers","title":"Liste des abonnés","description":"Liste des abonnés à la lettre d'information de la catégorie sélectionnée.","icon-small":"/plugins/newsletter/resources/img/subscriber/icon_small.png","icon-medium":"/plugins/newsletter/resources/img/subscriber/icon_medium.png","icon-large":"/plugins/newsletter/resources/img/subscriber/icon_large.png","default-location":"cl"}, {id: "org.ametys.newsletter.SubscribersFactory", pluginName: "newsletter"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-requeststracker","toolClass":"Ametys.plugins.coreui.system.requesttracker.RequestTrackerTool","title":"Suivi des requêtes serveur","description":"Voir les messages envoyés au serveur","help":"org.ametys.runtime.requesttracker","icon-small":"/plugins/core-ui/resources/img/requests/requests_16.png","icon-medium":"/plugins/core-ui/resources/img/requests/requests_32.png","icon-large":"/plugins/core-ui/resources/img/requests/requests_48.png","default-location":"b"}, {id: "org.ametys.runtime.userinterface.RequestTrackerFactory", pluginName: "core-ui"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"toolClass":"Ametys.plugins.skineditor.EditorTool","role":"uitool-skin-file-editor","title":"Fichier de paramètre","description":"Cet outil permet d'éditer un fichier de paramètre.","icon-small":"/plugins/cms/resources/img/params/editor/mixed_16.png","icon-medium":"/plugins/cms/resources/img/params/editor/mixed_32.png","icon-large":"/plugins/cms/resources/img/params/editor/mixed_48.png","default-location":""}, {id: "org.ametys.skineditor.editor.EditorTool", pluginName: "skineditor"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-page-attachments","toolClass":"Ametys.plugins.web.page.tool.PageAttachmentsTool","default-location":"r","title":"Pièces jointes","description":"Module de gestion des pièces jointes.<br/><br/>Ce module permet de lister, organiser, ajouter, supprimer ou télécharger les pièces jointes de la page courante.","help":"org.ametys.web.page.attachments","icon-small":"/plugins/web/resources/img/attach/icon_small.png","icon-medium":"/plugins/web/resources/img/attach/icon_medium.png","icon-large":"/plugins/web/resources/img/attach/icon_large.png"}, {id: "org.ametys.web.page.AttachmentsFactory", pluginName: "web"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"icon-medium":"/plugins/web/resources/img/skin/skin_32.png","inlineeditor-cssfile":[],"role":"uitool-admin-skin","icon-small":"/plugins/web/resources/img/skin/skin_16.png","toolClass":"Ametys.plugins.skinfactory.skin.SkinTool","icon-large":"/plugins/web/resources/img/skin/skin_48.png","default-location":"","description":"Gestion des chartes graphiques","title":"Chartes graphiques"}, {id: "org.ametys.web.skin.SkinToolFactory", pluginName: "skinfactory"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-groups","toolClass":"Ametys.plugins.core.groups.GroupsTool","title":"Groupes d'utilisateurs","description":"Liste des groupes et de leurs utilisateurs","help":"org.ametys.core.groups","icon-small":"/plugins/core/resources/img/groups/group_16.png","icon-medium":"/plugins/core/resources/img/groups/group_32.png","icon-large":"/plugins/core/resources/img/groups/group_50.png","default-location":""}, {id: "org.ametys.core.GroupsFactory", pluginName: "core"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"toolClass":"Ametys.plugins.explorer.applications.resources.ExplorerSearchTool","role":"uitool-explorer-search","title":"Recherche","description":"Recherche des ressources dans le dossier courant","icon-small":"/plugins/explorer/resources/img/resources/search_16.png","icon-medium":"/plugins/explorer/resources/img/resources/search_32.png","icon-large":"/plugins/explorer/resources/img/resources/search_48.png","default-location":"cl"}, {id: "org.ametys.plugins.explorer.applications.resources.ExplorerSearchToolFactory", pluginName: "explorer"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"toolClass":"Ametys.plugins.survey.LimitAccessTool","role":"uitool-survey-access","title":"Invitations","description":"Cliquez ici pour sélectionner les utilisateurs autorisés à répondre à l'enquête privée.","icon-small":"/plugins/survey/resources/img/survey/granted_user_16.png","icon-medium":"/plugins/survey/resources/img/survey/granted_user_32.png","icon-large":"/plugins/survey/resources/img/survey/granted_user_48.png","default-location":"cl"}, {id: "org.ametys.survey.LimitAccessFactory", pluginName: "survey"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"toolClass":"Ametys.plugins.glossary.GlossaryTool","role":"uitool-glossary","title":"Glossaire","description":"Interface de gestion des définitions du glossaire.","icon-small":"/plugins/glossary/resources/img/glossary-16.png","icon-medium":"/plugins/glossary/resources/img/glossary-32.png","icon-large":"/plugins/glossary/resources/img/glossary-48.png","default-location":"cl"}, {id: "org.ametys.plugins.glossary.ui.GlossaryToolFactory", pluginName: "glossary"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-global-consistency","toolClass":"Ametys.plugins.web.content.tool.GlobalConsistencyTool","title":"Rapport des liens cassés","description":"Visualisation du dernier rapport des liens cassés.","help":"org.ametys.cms.content.consistency","icon-small":"/plugins/cms/resources/img/consistency/consistency_16.png","icon-medium":"/plugins/cms/resources/img/consistency/consistency_32.png","icon-large":"/plugins/cms/resources/img/consistency/properties_48.png"}, {id: "org.ametys.web.GlobalConsistencyTool", pluginName: "web"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-consistency","toolClass":"Ametys.plugins.cms.content.tool.ConsistencyTool","title":"Liens cassés","description":"Affiche les liens cassés du ou des contenus sélectionnés","help":"org.ametys.cms.content.consistency","selection-target-type":"^content$","selection-description-empty":"Aucun contenu n'est actuellement sélectionné.<br/>Sélectionnez un contenu pour obtenir plus d'informations.","selection-description-nomatch":"Aucun contenu n'est actuellement sélectionné.<br/>Sélectionnez un contenu pour obtenir plus d'informations.","selection-description-multiselectionforbidden":"Plusieurs contenus sont actuellement sélectionnés.<br/>Sélectionnez un seul contenu pour obtenir plus d'informations.","icon-small":"/plugins/cms/resources/img/consistency/properties_16.png","icon-medium":"/plugins/cms/resources/img/consistency/properties_32.png","icon-large":"/plugins/cms/resources/img/consistency/properties_48.png","default-location":"l"}, {id: "org.ametys.cms.ConsistencyFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"toolClass":"Ametys.plugins.explorer.applications.threads.ThreadTool","role":"uitool-explorer-thread","title":"Chargement fil...","description":"Affichage du fil de discussion","icon-small":"/plugins/explorer/resources/img/thread/thread_16.png","icon-medium":"/plugins/explorer/resources/img/thread/thread_32.png","icon-large":"/plugins/explorer/resources/img/thread/thread_48.png","default-location":"cl"}, {id: "org.ametys.plugins.explorer.applications.threads.ThreadToolFactory", pluginName: "explorer"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"toolClass":"Ametys.plugins.explorer.applications.calendars.CalendarTool","role":"uitool-explorer-calendar","title":"Chargement calendrier...","description":"Affichage du calendrier","icon-small":"/plugins/explorer/resources/img/calendar/icon_small.png","icon-medium":"/plugins/explorer/resources/img/calendar/icon_medium.png","icon-large":"/plugins/explorer/resources/img/calendar/icon_large.png","default-location":"cl"}, {id: "org.ametys.plugins.explorer.applications.calendars.CalendarToolFactory", pluginName: "explorer"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"toolClass":"Ametys.plugins.explorer.applications.resources.ResourceCollectionTool","role":"uitool-explorer-resource-collection","title":"Chargement dossier...","description":"Vue du dossier de l'explorateur","icon-small":"/plugins/explorer/resources/img/explorer_16.png","icon-medium":"/plugins/explorer/resources/img/explorer_32.png","icon-large":"/plugins/explorer/resources/img/explorer_48.png","default-location":"cl"}, {id: "org.ametys.plugins.explorer.applications.resources.ResourceCollectionToolFactory", pluginName: "explorer"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"toolClass":"Ametys.plugins.survey.SurveyStatisticsTool","selection-target-type":"^survey$","role":"uitool-survey-statistics","autoRefresh":"false","title":"Statistiques de l'enquête","description":"Statistiques de l'enquête sélectionnée.","icon-small":"/plugins/survey/resources/img/survey/survey_16.png","icon-medium":"/plugins/survey/resources/img/survey/survey_32.png","icon-large":"/plugins/survey/resources/img/survey/survey_48.png","default-location":"cl"}, {id: "org.ametys.survey.StatisticsTool", pluginName: "survey"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"toolClass":"Ametys.plugins.survey.SurveyTool","role":"uitool-survey","title":"Enquêtes en ligne","description":"Outil de gestion des enquêtes en ligne","icon-small":"/plugins/survey/resources/img/survey/survey_16.png","icon-medium":"/plugins/survey/resources/img/survey/survey_32.png","icon-large":"/plugins/survey/resources/img/survey/survey_48.png","default-location":"l"}, {id: "org.ametys.survey.SurveyToolFactory", pluginName: "survey"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"toolClass":"Ametys.plugins.survey.SurveyPreviewTool","role":"uitool-survey-preview","title":"Prévisualisation","description":"Prévisualisation de l'enquête en ligne","icon-small":"/plugins/survey/resources/img/survey/preview_16.png","icon-medium":"/plugins/survey/resources/img/survey/preview_32.png","icon-large":"/plugins/survey/resources/img/survey/preview_48.png","default-location":"cl"}, {id: "org.ametys.survey.SurveyPreviewToolFactory", pluginName: "survey"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-user-rights","toolClass":"Ametys.plugins.core.users.UserRightsTool","title":"Voir les droits","description":"Droits de l'utilisateur sélectionné","selection-target-type":"^user$","selection-description-empty":"Aucun utilisateur n'est actuellement sélectionné.<br/>Sélectionnez un utilisateur pour visualiser ses droits.","selection-description-nomatch":"Aucun utilisateur n'est actuellement sélectionné.<br/>Sélectionnez un utilisateur pour visualiser ses droits.","selection-description-multiselectionforbidden":"Plusieurs utilisateurs sont actuellement sélectionnés.<br/>Sélectionnez un utilisateur pour visualiser ses droits.","help":"org.ametys.core.users.rights","icon-small":"/plugins/core/resources/img/users/rights_16.png","icon-medium":"/plugins/core/resources/img/users/rights_32.png","icon-large":"/plugins/core/resources/img/users/rights_48.png","default-location":"r"}, {id: "org.ametys.core.UserRightsFactory", pluginName: "core"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-users","toolClass":"Ametys.plugins.core.users.UsersTool","title":"Utilisateurs","description":"Gestion des utilisateurs de l'application<br/>Cet outil vous permet de créer, modifier, rechercher les utilisateurs.<br/>Attention ! La recherche ne renvoie que 100 résultats.","help":"org.ametys.core.users","icon-small":"/plugins/core/resources/img/users/user_16.png","icon-medium":"/plugins/core/resources/img/users/user_32.png","icon-large":"/plugins/core/resources/img/users/user_48.png","default-location":""}, {id: "org.ametys.core.UsersFactory", pluginName: "core"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-repository-jcr","toolClass":"Ametys.repository.JcrViewTool","title":"Vue JCR","description":"Vue JCR","help":"org.ametys.repository.jcrview","icon-small":"/plugins/repositoryapp/resources/img/jcr/jcr-view-16.png","icon-medium":"/plugins/repositoryapp/resources/img/jcr/jcr-view-32.png","icon-large":"/plugins/repositoryapp/resources/img/jcr/jcr-view-48.png","default-location":"l"}, {id: "org.ametys.repository.ui.JcrViewTool", pluginName: "repositoryapp"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"role":"uitool-repository-nodeproperties","toolClass":"Ametys.repository.NodePropertiesTool","title":"Propriétés","description":"Propriétés du noeud","help":"org.ametys.repository.nodeproperties","icon-small":"/plugins/repositoryapp/resources/img/jcr/node-properties-16.png","icon-medium":"/plugins/repositoryapp/resources/img/jcr/node-properties-32.png","icon-large":"/plugins/repositoryapp/resources/img/jcr/node-properties-48.png","default-location":""}, {id: "org.ametys.repository.ui.NodePropertiesTool", pluginName: "repositoryapp"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-repository-descriptors","toolClass":"Ametys.repository.RepositoryDescriptorsTool","title":"Propriétés du repository","description":"Cet outil présente la liste des descripteurs du repository et de leurs valeurs.","help":"org.ametys.repository.descriptors","icon-small":"/plugins/repositoryapp/resources/img/descriptors/descriptors-16.png","icon-medium":"/plugins/repositoryapp/resources/img/descriptors/descriptors-32.png","icon-large":"/plugins/repositoryapp/resources/img/descriptors/descriptors-48.png","default-location":""}, {id: "org.ametys.repository.ui.RepositoryDescriptorsTool", pluginName: "repositoryapp"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"toolClass":"Ametys.plugins.cms.contenttype.ContentTypeHierarchyTool","role":"uitool-contenttypes","title":"Types de contenu","description":"Arbre des types de contenus déclarés dans l'application","help":"org.ametys.cms.contenttype.hierarchy","icon-small":"/plugins/cms/resources/img/contenttype/tree_16.png","icon-medium":"/plugins/cms/resources/img/contenttype/tree_32.png","icon-large":"/plugins/cms/resources/img/contenttype/tree_48.png","default-location":"l"}, {id: "org.ametys.cms.contenttype.HierarchyFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.BasicToolFactory", Ext.apply({"icon-medium":"/plugins/cms/resources/img/content/content_32.png","inlineeditor-cssfile":[],"role":"uitool-content","icon-small":"/plugins/cms/resources/img/content/content_16.png","toolClass":"Ametys.plugins.web.content.tool.ContentTool","icon-large":"/plugins/cms/resources/img/content/content_48.png","default-location":"","description":"<u>Auteur</u> : <b></b><br/><u>Dernière modification</u> :<b></b>","description-footer":"Voir l'aide pour plus de détails"}, {id: "org.ametys.web.ContentFactory", pluginName: "web"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-admin-logs","toolClass":"Ametys.plugins.admin.logs.LogsTool","title":"Visualisation","description":"Visualiser les journaux de l'application","icon-small":"/plugins/admin/resources/img/logs/logs_16.png","icon-medium":"/plugins/admin/resources/img/logs/logs_32.png","icon-large":"/plugins/admin/resources/img/logs/logs_48.png","default-location":"cl"}, {id: "org.ametys.plugins.admin.logs.LogsFactory", pluginName: "admin"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-admin-logslevel","toolClass":"Ametys.plugins.admin.logs.LogsLevelTool","title":"Configuration","description":"Cet outil permet de configurer les niveaux de logs catégorie par catégorie.<br/>Pour modifier de manière permanente le niveau de logs, configurez le fichier WEB-INF\\\\log4j.xml.","icon-small":"/plugins/admin/resources/img/logs/loglevel_16.png","icon-medium":"/plugins/admin/resources/img/logs/loglevel_32.png","icon-large":"/plugins/admin/resources/img/logs/loglevel_48.png","default-location":"cl"}, {id: "org.ametys.plugins.admin.logs.LogsLevelFactory", pluginName: "admin"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-history","toolClass":"Ametys.plugins.cms.content.tool.HistoryTool","title":"Historique","description":"Historique du contenu : workflow et versions","help":"org.ametys.cms.content.history","selection-target-type":"^(content|old-content)$","selection-description-empty":"Aucun contenu n'est actuellement sélectionné.<br/>Sélectionnez un contenu pour voir son historique.","selection-description-nomatch":"Aucun contenu n'est actuellement sélectionné.<br/>Sélectionnez un contenu pour voir son historique.","selection-description-multiselectionforbidden":"Plusieurs contenus sont actuellement sélectionnés.<br/>Sélectionnez un contenu pour son historique.","icon-small":"/plugins/cms/resources/img/history/history_16.png","icon-medium":"/plugins/cms/resources/img/history/history_32.png","icon-large":"/plugins/cms/resources/img/history/history_50.png","default-location":"l"}, {id: "org.ametys.cms.userinterface.HistoryFactory", pluginName: "cms"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-admin-pluginsbyextensionpoint","toolClass":"Ametys.plugins.admin.plugins.PluginsTool","proxyUrl":"plugins-by-extension-point","title":"Plugins par point d'extension","description":"Ouvre un outil permettant de visualiser les plugins par point d'extension sous forme d'un arbre. Permet d'activer/désactiver des plugins.","icon-small":"/plugins/admin/resources/img/plugins/plugins_ep_16.png","icon-medium":"/plugins/admin/resources/img/plugins/plugins_ep_32.png","icon-large":"/plugins/admin/resources/img/plugins/plugins_ep_48.png"}, {id: "org.ametys.plugins.admin.PluginsByExtensionPointFactory", pluginName: "admin"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-admin-pluginsbyfile","toolClass":"Ametys.plugins.admin.plugins.PluginsTool","proxyUrl":"plugins-by-file","title":"Plugins par fichier","description":"Ouvre un outil permettant de visualiser les plugins par fichiers sous forme d'un arbre. Permet d'activer/désactiver des plugins.","icon-small":"/plugins/admin/resources/img/plugins/plugins_16.png","icon-medium":"/plugins/admin/resources/img/plugins/plugins_32.png","icon-large":"/plugins/admin/resources/img/plugins/plugins_48.png"}, {id: "org.ametys.plugins.admin.PluginsByFileFactory", pluginName: "admin"}));
   Ametys.tool.ToolsManager.addFactory(factory);

   factory = Ext.create("Ametys.tool.factory.UniqueToolFactory", Ext.apply({"role":"uitool-admin-workspaces","toolClass":"Ametys.plugins.admin.tool.WorkspacesTool","title":"Workspaces","description":"Ouvre un outil permettant de visualiser les workspaces sous forme d'un arbre.","icon-small":"/plugins/admin/resources/img/plugins/workspaces_16.png","icon-medium":"/plugins/admin/resources/img/plugins/workspaces_32.png","icon-large":"/plugins/admin/resources/img/plugins/workspaces_48.png"}, {id: "org.ametys.plugins.admin.WorkspacesFactory", pluginName: "admin"}));
   Ametys.tool.ToolsManager.addFactory(factory);
